# Generated by Django 5.1.3 on 2024-11-28 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_code', models.CharField(max_length=7, unique=True)),
                ('established_date', models.DateField()),
                ('total_capital', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('person', 'Physical Person'), ('company', 'Company')], max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('entity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_reg_code', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyShareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_share', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_founder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='business_registry.company')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='business_registry.shareholder')),
            ],
        ),
    ]
