# Generated by Django 5.1.3 on 2024-11-26 13:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_founder', models.BooleanField(default=False)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_registry.legalentity')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_registry.person')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('registration_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(7)])),
                ('establishment_date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 11, 26))])),
                ('total_capital', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2500)])),
                ('shareholders', models.ManyToManyField(related_name='companies', to='business_registry.shareholder')),
            ],
        ),
    ]
