# Generated by Django 5.1.3 on 2024-11-27 07:32

import business_registry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsaUhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(help_text='Sisesta nimi, 3 kuni 100 tähte või numbrit.', max_length=100, unique=True, validators=[business_registry.models.validate_nimi])),
                ('registrikood', models.CharField(help_text='Registrikood peab olema täpselt 7 numbrit.', max_length=7, unique=True)),
                ('asutamiskuupaev', models.DateField(help_text='Asutamiskuupäev peab olema väiksem või võrdne tänase kuupäevaga.')),
                ('kogukapital', models.PositiveIntegerField(help_text='Kogukapitali suurus peab olema vähemalt 2500 eurot.', validators=[business_registry.models.validate_kogukapital])),
            ],
        ),
        migrations.CreateModel(
            name='Osanik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(help_text='Osaniku nimi.', max_length=100)),
                ('osa_suurus', models.PositiveIntegerField(help_text='Osaniku osa suurus eurodes (vähemalt 1).')),
                ('osa_uhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osanikud', to='business_registry.osauhing')),
            ],
        ),
    ]
