# Generated by Django 5.1.3 on 2024-11-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shareholders',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='business_registry.company'),
        ),
    ]
