# Generated by Django 5.1.3 on 2024-11-27 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='identification_code',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
