# Generated by Django 5.1.3 on 2024-11-27 07:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registry', '0002_remove_company_shareholders_shareholder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 11, 27))]),
        ),
    ]
